actions:
  1:
    action: delete_indices
    description: >-
      Supprime les indices.
      utiliser les filtres pour prévenir la supression inférieur à ${UNIT_COUNT} jours .
     Ignorer les erreurs si le filtre ne retourne pas une list d'indince utilisable (ignore_empty_list)
      et quitter 
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: ${UNIT_COUNT}
