ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# Ajouter les plugins elastic pour install dessous 
# Exemple : RUN elasticsearch-plugin install analysis-icu
