ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# ajouter les installation de plugin logstash ici 
# Exemple: RUN logstash-plugin install logstash-filter-json
